FROM amazoncorretto:latest
CMD ["/usr/sbin/init"]
RUN yum update -y &&\
      yum install -y wget java-1.8.0-openjdk curl initscripts
RUN wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
RUN rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
RUN yum update -y &&\
       yum install -y jenkins
EXPOSE 8080
ENTRYPOINT ["tail"]
CMD ["-f", "/dev/null"]